# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\rgaming.events\"\xea\x01\n\tGameEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12,\n\nevent_type\x18\x02 \x01(\x0e\x32\x18.gaming.events.EventType\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x38\n\x08metadata\x18\x06 \x03(\x0b\x32&.gaming.events.GameEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xac\x01\n\x0cWeatherEvent\x12\x11\n\told_state\x18\x01 \x01(\t\x12\x11\n\tnew_state\x18\x02 \x01(\t\x12\x11\n\tintensity\x18\x03 \x01(\x02\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x12\n\nwind_speed\x18\x05 \x01(\x02\x12\x10\n\x08humidity\x18\x06 \x01(\x02\x12\x0e\n\x06season\x18\x07 \x01(\t\x12\x18\n\x10\x64uration_minutes\x18\x08 \x01(\x05\"q\n\tTimeEvent\x12\x11\n\told_state\x18\x01 \x01(\t\x12\x11\n\tnew_state\x18\x02 \x01(\t\x12\x0c\n\x04hour\x18\x03 \x01(\x05\x12\x0e\n\x06minute\x18\x04 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x05 \x01(\x05\x12\x13\n\x0btime_string\x18\x06 \x01(\t\"\x86\x01\n\x0bStateUpdate\x12\x34\n\x05state\x18\x01 \x03(\x0b\x32%.gaming.events.StateUpdate.StateEntry\x12\x13\n\x0bupdate_type\x18\x02 \x01(\t\x1a,\n\nStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xbf\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fWEATHER_CHANGED\x10\x01\x12\x12\n\x0eWEATHER_SEVERE\x10\x02\x12\x10\n\x0cTIME_CHANGED\x10\x03\x12\x16\n\x12TIME_DAY_ACTIVATED\x10\x04\x12\x18\n\x14TIME_NIGHT_ACTIVATED\x10\x05\x12\x10\n\x0cTIME_UPDATED\x10\x06\x12\x17\n\x13WORLD_STATE_UPDATED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEEVENT_METADATAENTRY']._loaded_options = None
  _globals['_GAMEEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STATEUPDATE_STATEENTRY']._loaded_options = None
  _globals['_STATEUPDATE_STATEENTRY']._serialized_options = b'8\001'
  _globals['_EVENTTYPE']._serialized_start=696
  _globals['_EVENTTYPE']._serialized_end=887
  _globals['_GAMEEVENT']._serialized_start=32
  _globals['_GAMEEVENT']._serialized_end=266
  _globals['_GAMEEVENT_METADATAENTRY']._serialized_start=219
  _globals['_GAMEEVENT_METADATAENTRY']._serialized_end=266
  _globals['_WEATHEREVENT']._serialized_start=269
  _globals['_WEATHEREVENT']._serialized_end=441
  _globals['_TIMEEVENT']._serialized_start=443
  _globals['_TIMEEVENT']._serialized_end=556
  _globals['_STATEUPDATE']._serialized_start=559
  _globals['_STATEUPDATE']._serialized_end=693
  _globals['_STATEUPDATE_STATEENTRY']._serialized_start=649
  _globals['_STATEUPDATE_STATEENTRY']._serialized_end=693
# @@protoc_insertion_point(module_scope)
