# Automated New Project Setup Script
# This script automates the setup of a new Cursor project with all global configurations

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectName,
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectType = "Website",
    
    [Parameter(Mandatory=$false)]
    [string]$CustomerName = ""
)

Write-Host "`n=== AUTOMATED PROJECT SETUP ===" -ForegroundColor Cyan
Write-Host "Project: $ProjectName" -ForegroundColor White
Write-Host "Type: $ProjectType" -ForegroundColor White

# Auto-detect customer name from parent folder if not provided
if (-not $CustomerName) {
    $parentFolder = Split-Path (Get-Location) -Leaf
    if ($parentFolder -ne (Split-Path $ProjectName -Leaf)) {
        $CustomerName = $parentFolder
        Write-Host "Customer: $CustomerName (auto-detected)" -ForegroundColor White
    }
}

# Calculate database and package names
$dbName = if ($CustomerName) {
    ($CustomerName.ToLower() -replace '\s+', '_') + "_" + ($ProjectName.ToLower() -replace '\s+', '_')
} else {
    ($ProjectName.ToLower() -replace '\s+', '_')
}

$packageName = if ($CustomerName) {
    ($CustomerName.ToLower() -replace '\s+', '-') + "-" + ($ProjectName.ToLower() -replace '\s+', '-')
} else {
    ($ProjectName.ToLower() -replace '\s+', '-')
}

Write-Host "Database: $dbName" -ForegroundColor Green
Write-Host "Package: $packageName" -ForegroundColor Green

# Step 1: Update project-config.md
Write-Host "`n[1/7] Updating project-config.md..." -ForegroundColor Yellow
if (Test-Path "project-config.md") {
    $config = Get-Content "project-config.md" -Raw
    $config = $config -replace 'Project Name: .*', "Project Name: $ProjectName"
    $config = $config -replace 'Database Name: .*', "Database Name: $dbName"
    $config = $config -replace 'Package Name: .*', "Package Name: $packageName"
    $config | Out-File "project-config.md" -Encoding UTF8 -NoNewline
    Write-Host "   ✓ project-config.md updated" -ForegroundColor Green
}

# Step 2: Update package.json
Write-Host "`n[2/7] Updating package.json..." -ForegroundColor Yellow
if (Test-Path "package.json") {
    $package = Get-Content "package.json" -Raw | ConvertFrom-Json
    $package.name = $packageName
    $package.description = "$ProjectName - $ProjectType"
    $package | ConvertTo-Json -Depth 10 | Out-File "package.json" -Encoding UTF8
    Write-Host "   ✓ package.json updated" -ForegroundColor Green
}

# Step 3: Create .env file from template
Write-Host "`n[3/7] Creating .env file..." -ForegroundColor Yellow
if (Test-Path "$env:USERPROFILE\.cursor\Deployment\Global\.env.txt") {
    Copy-Item "$env:USERPROFILE\.cursor\Deployment\Global\.env.txt" ".env" -Force
    
    # Add project-specific values
    Add-Content ".env" "`n# Project Configuration"
    Add-Content ".env" "DB_NAME=$dbName"
    Add-Content ".env" "PROJECT_NAME=$ProjectName"
    
    Write-Host "   ✓ .env created (fill in your API keys)" -ForegroundColor Green
} else {
    Write-Host "   ⚠ .env template not found, skipping" -ForegroundColor Yellow
}

# Step 4: Link global repository
Write-Host "`n[4/7] Linking global repository..." -ForegroundColor Yellow
if (Test-Path "scripts\Sync-Global-Rules.ps1") {
    & ".\scripts\Sync-Global-Rules.ps1" -Force
    Write-Host "   ✓ Global repository linked" -ForegroundColor Green
} else {
    Write-Host "   ⚠ Sync-Global-Rules.ps1 not found" -ForegroundColor Yellow
}

# Step 5: Initialize Git repository
Write-Host "`n[5/7] Initializing Git repository..." -ForegroundColor Yellow
if (-not (Test-Path ".git")) {
    git init
    Write-Host "   ✓ Git repository initialized" -ForegroundColor Green
} else {
    Write-Host "   ✓ Git repository already exists" -ForegroundColor Green
}

# Step 6: Create initial commit
Write-Host "`n[6/7] Creating initial commit..." -ForegroundColor Yellow
git add -A
git commit -m "chore: initial project setup for $ProjectName

Project Type: $ProjectType
Database: $dbName
Package: $packageName

Generated by automated setup script"

Write-Host "   ✓ Initial commit created" -ForegroundColor Green

# Step 7: Run startup script
Write-Host "`n[7/7] Running startup script..." -ForegroundColor Yellow
if (Test-Path "startup.ps1") {
    & ".\startup.ps1"
    Write-Host "   ✓ Startup complete" -ForegroundColor Green
} else {
    Write-Host "   ⚠ startup.ps1 not found" -ForegroundColor Yellow
}

# Done!
Write-Host "`n=== SETUP COMPLETE ===" -ForegroundColor Cyan
Write-Host "`n📋 Next Steps:" -ForegroundColor Yellow
Write-Host "1. Edit .env file and add your API keys" -ForegroundColor White
Write-Host "2. Update package.json with additional dependencies" -ForegroundColor White
Write-Host "3. Run: npm install" -ForegroundColor White
Write-Host "4. Create your Docker environment: docker-compose up -d" -ForegroundColor White
Write-Host "5. Start development: npm run dev" -ForegroundColor White
Write-Host "`n📝 Project Details:" -ForegroundColor Yellow
Write-Host "  Name: $ProjectName" -ForegroundColor White
Write-Host "  Database: $dbName" -ForegroundColor White
Write-Host "  Package: $packageName" -ForegroundColor White
Write-Host "`n✨ Your project is ready!" -ForegroundColor Green

