AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified Aurora PostgreSQL for Gaming System AI Core'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for database deployment

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnet IDs for database cluster (min 2 AZs)

  ApplicationSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID of the application tier

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # Database Secrets
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-db-credentials
      Description: Aurora PostgreSQL database credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${AWS::StackName}-subnet-group
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL cluster
      SubnetIds: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet-group

  # Security Group for Database
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-db-sg
      GroupDescription: Security group for Aurora PostgreSQL cluster
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ApplicationSecurityGroupId
          Description: Allow access from application tier
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-sg

  # DB Cluster Parameter Group
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Optimized for gaming workloads
      Family: aurora-postgresql15
      Parameters:
        max_connections: '1000'
        shared_preload_libraries: 'pg_stat_statements'
        log_statement: 'ddl'
        log_min_duration_statement: '1000'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-cluster-params

  # Aurora PostgreSQL Cluster
  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      DBClusterIdentifier: !Sub ${AWS::StackName}-cluster
      Engine: aurora-postgresql
      EngineVersion: '15.13'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
      DatabaseName: gaming_system_ai_core
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      PreferredMaintenanceWindow: sun:05:00-sun:06:00
      PreferredBackupWindow: 03:00-04:00
      EnableCloudwatchLogsExports:
        - postgresql
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-cluster
        - Key: Environment
          Value: !Ref Environment

  # Primary Writer Instance
  DBInstanceWriter:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-writer
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !If
        - IsProduction
        - db.r6g.2xlarge
        - db.r6g.large
      Engine: aurora-postgresql
      PromotionTier: 0
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-writer
        - Key: Role
          Value: Writer

  # Read Replica
  DBInstanceReader1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-reader-1
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !If
        - IsProduction
        - db.r6g.xlarge
        - db.r6g.large
      Engine: aurora-postgresql
      PromotionTier: 1
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-reader-1
        - Key: Role
          Value: Reader

Outputs:
  DBClusterEndpoint:
    Description: Aurora cluster endpoint (writer)
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-cluster-endpoint

  DBClusterReadEndpoint:
    Description: Aurora cluster read endpoint
    Value: !GetAtt DBCluster.ReadEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-read-endpoint

  DBSecretArn:
    Description: Secrets Manager ARN for database credentials
    Value: !Ref DBSecret
    Export:
      Name: !Sub ${AWS::StackName}-secret-arn

  DBName:
    Description: Database name
    Value: gaming_system_ai_core
    Export:
      Name: !Sub ${AWS::StackName}-database-name

  DBPort:
    Description: Database port
    Value: '5432'
    Export:
      Name: !Sub ${AWS::StackName}-port
