-- P0-5 CRITICAL FIX: PostgreSQL schema for persistent report storage
-- Replaces in-memory storage to prevent data loss on restart

-- Reports table
CREATE TABLE IF NOT EXISTS reports (
    id VARCHAR(100) PRIMARY KEY,
    test_run_id VARCHAR(100) NOT NULL,
    game_title VARCHAR(200) NOT NULL,
    game_version VARCHAR(50),
    test_environment VARCHAR(200) NOT NULL,
    format VARCHAR(10) NOT NULL CHECK (format IN ('json', 'html', 'pdf')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
    
    -- S3 storage
    s3_bucket VARCHAR(200),
    s3_key VARCHAR(500),
    file_size_bytes BIGINT DEFAULT 0,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    
    -- Error tracking
    error_message TEXT,
    
    -- Performance
    duration_seconds DECIMAL(10, 2),
    
    -- Report data (JSONB for flexible querying)
    report_data JSONB,
    
    -- Indexes
    CONSTRAINT valid_timestamps CHECK (
        started_at IS NULL OR started_at >= created_at
    ),
    CONSTRAINT valid_completion CHECK (
        completed_at IS NULL OR completed_at >= created_at
    )
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_reports_test_run_id ON reports(test_run_id);
CREATE INDEX IF NOT EXISTS idx_reports_game_title ON reports(game_title);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_game_title_created ON reports(game_title, created_at DESC);

-- JSONB indexes for report data queries
CREATE INDEX IF NOT EXISTS idx_reports_data_summary ON reports USING GIN ((report_data->'summary'));
CREATE INDEX IF NOT EXISTS idx_reports_data_issues ON reports USING GIN ((report_data->'consensus_issues'));

-- Report artifacts table (for tracking multiple format versions)
CREATE TABLE IF NOT EXISTS report_artifacts (
    id SERIAL PRIMARY KEY,
    report_id VARCHAR(100) NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    format VARCHAR(10) NOT NULL CHECK (format IN ('json', 'html', 'pdf')),
    s3_bucket VARCHAR(200) NOT NULL,
    s3_key VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    checksum VARCHAR(64),  -- SHA-256 checksum
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    UNIQUE(report_id, format)
);

CREATE INDEX IF NOT EXISTS idx_artifacts_report_id ON report_artifacts(report_id);

-- Report events table (audit trail)
CREATE TABLE IF NOT EXISTS report_events (
    id SERIAL PRIMARY KEY,
    report_id VARCHAR(100) NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL CHECK (event_type IN (
        'queued', 'started', 'data_collected', 'data_transformed', 
        'html_generated', 'pdf_generated', 'stored', 'completed', 'failed'
    )),
    message TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_report_id ON report_events(report_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON report_events(created_at DESC);

-- Cache cleanup function (for scheduled maintenance)
CREATE OR REPLACE FUNCTION cleanup_old_reports(retention_days INT DEFAULT 30)
RETURNS INT AS $$
DECLARE
    deleted_count INT;
BEGIN
    -- Delete reports older than retention period
    WITH deleted AS (
        DELETE FROM reports
        WHERE created_at < NOW() - (retention_days || ' days')::INTERVAL
        AND status IN ('completed', 'failed')
        RETURNING id
    )
    SELECT COUNT(*) INTO deleted_count FROM deleted;
    
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- View for quick statistics
CREATE OR REPLACE VIEW report_statistics AS
SELECT
    game_title,
    COUNT(*) as total_reports,
    COUNT(*) FILTER (WHERE status = 'completed') as completed,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COUNT(*) FILTER (WHERE status = 'processing') as processing,
    COUNT(*) FILTER (WHERE status = 'queued') as queued,
    AVG(duration_seconds) FILTER (WHERE status = 'completed') as avg_duration_seconds,
    MAX(created_at) as last_report_at
FROM reports
GROUP BY game_title;

-- Comments for documentation
COMMENT ON TABLE reports IS 'Validation reports generated by AI testing system';
COMMENT ON TABLE report_artifacts IS 'Individual report format artifacts (JSON, HTML, PDF)';
COMMENT ON TABLE report_events IS 'Audit trail for report generation pipeline';
COMMENT ON FUNCTION cleanup_old_reports IS 'Cleanup reports older than retention period';

