# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto. import language_service_pb2 as language__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in language_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanguageServiceStub(object):
    """Language System gRPC Service
    Provides language generation, translation, and interpretation services

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSentence = channel.unary_unary(
                '/language_system.LanguageService/GenerateSentence',
                request_serializer=language__service__pb2.GenerateSentenceRequest.SerializeToString,
                response_deserializer=language__service__pb2.GenerateSentenceResponse.FromString,
                _registered_method=True)
        self.GenerateSentenceStream = channel.unary_stream(
                '/language_system.LanguageService/GenerateSentenceStream',
                request_serializer=language__service__pb2.GenerateSentenceRequest.SerializeToString,
                response_deserializer=language__service__pb2.SentenceToken.FromString,
                _registered_method=True)
        self.Translate = channel.unary_unary(
                '/language_system.LanguageService/Translate',
                request_serializer=language__service__pb2.TranslateRequest.SerializeToString,
                response_deserializer=language__service__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.Interpret = channel.unary_unary(
                '/language_system.LanguageService/Interpret',
                request_serializer=language__service__pb2.InterpretRequest.SerializeToString,
                response_deserializer=language__service__pb2.InterpretResponse.FromString,
                _registered_method=True)
        self.ListLanguages = channel.unary_unary(
                '/language_system.LanguageService/ListLanguages',
                request_serializer=language__service__pb2.ListLanguagesRequest.SerializeToString,
                response_deserializer=language__service__pb2.ListLanguagesResponse.FromString,
                _registered_method=True)
        self.GetLanguage = channel.unary_unary(
                '/language_system.LanguageService/GetLanguage',
                request_serializer=language__service__pb2.GetLanguageRequest.SerializeToString,
                response_deserializer=language__service__pb2.GetLanguageResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/language_system.LanguageService/HealthCheck',
                request_serializer=language__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=language__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class LanguageServiceServicer(object):
    """Language System gRPC Service
    Provides language generation, translation, and interpretation services

    """

    def GenerateSentence(self, request, context):
        """Generate a sentence in a specific language
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSentenceStream(self, request, context):
        """Stream sentence generation (for real-time dialogue)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Translate(self, request, context):
        """Translate text between languages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interpret(self, request, context):
        """Provide contextual interpretation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLanguages(self, request, context):
        """List all available languages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLanguage(self, request, context):
        """Get language definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSentence,
                    request_deserializer=language__service__pb2.GenerateSentenceRequest.FromString,
                    response_serializer=language__service__pb2.GenerateSentenceResponse.SerializeToString,
            ),
            'GenerateSentenceStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateSentenceStream,
                    request_deserializer=language__service__pb2.GenerateSentenceRequest.FromString,
                    response_serializer=language__service__pb2.SentenceToken.SerializeToString,
            ),
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=language__service__pb2.TranslateRequest.FromString,
                    response_serializer=language__service__pb2.TranslateResponse.SerializeToString,
            ),
            'Interpret': grpc.unary_unary_rpc_method_handler(
                    servicer.Interpret,
                    request_deserializer=language__service__pb2.InterpretRequest.FromString,
                    response_serializer=language__service__pb2.InterpretResponse.SerializeToString,
            ),
            'ListLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLanguages,
                    request_deserializer=language__service__pb2.ListLanguagesRequest.FromString,
                    response_serializer=language__service__pb2.ListLanguagesResponse.SerializeToString,
            ),
            'GetLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLanguage,
                    request_deserializer=language__service__pb2.GetLanguageRequest.FromString,
                    response_serializer=language__service__pb2.GetLanguageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=language__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=language__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'language_system.LanguageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('language_system.LanguageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanguageService(object):
    """Language System gRPC Service
    Provides language generation, translation, and interpretation services

    """

    @staticmethod
    def GenerateSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/GenerateSentence',
            language__service__pb2.GenerateSentenceRequest.SerializeToString,
            language__service__pb2.GenerateSentenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSentenceStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/language_system.LanguageService/GenerateSentenceStream',
            language__service__pb2.GenerateSentenceRequest.SerializeToString,
            language__service__pb2.SentenceToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/Translate',
            language__service__pb2.TranslateRequest.SerializeToString,
            language__service__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interpret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/Interpret',
            language__service__pb2.InterpretRequest.SerializeToString,
            language__service__pb2.InterpretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/ListLanguages',
            language__service__pb2.ListLanguagesRequest.SerializeToString,
            language__service__pb2.ListLanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/GetLanguage',
            language__service__pb2.GetLanguageRequest.SerializeToString,
            language__service__pb2.GetLanguageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/language_system.LanguageService/HealthCheck',
            language__service__pb2.HealthCheckRequest.SerializeToString,
            language__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
